### ISSUE TITLE
Postgre instead of mysql

### ISSUE THREAD

**Issue by r3dlin3** [jhipster/jhipster-devbox#22]
jhipster is proposing to use H2 or postgre as a dev database and not mysql.
The "fast" profile recommends to use a non-memory database.
Would it not be nice to have postgre instead mysql (or both)?

**Comment by jdubois** [comment]
This has been discussed before, but yes I guess we could add Postgresql, it's not such a big deal. And we would need PGAdmin III also, of course.

**Comment by cbornet** [comment]
Could we install docker instead ? Once you have seen the magic of ```docker-compose up -d```, you don't want to install a dev db another way anymore

**Comment by pascalgrimaud** [comment]
@cbornet : yes it was the initial idea, but my first PR failed when installing docker+docker-compose :whale: for unknown reason (maybe because m2) => I should do a separate PR

Since this PR, I didn't work on adding docker because my connection sux.. 1h30~2h to test and install the VM. So your PR will be welcome

**Comment by jdubois** [comment]
As we are going "full Docker" I'm closing this! So yes it's going to be done, through Docker.
